// Generated by CoffeeScript 1.6.3
(function() {
  var app, express;

  express = require('express');

  app = express();

  app.set('port', process.env.PORT || 5000);

  app.use(express["static"](__dirname + '/public'));

  app.get('/', function(request, response) {
    return response.send('heyyyy yahhhhh!');
  });

  app.listen(app.get('port'), function() {
    return console.log('node is running on localhost:' + app.get('port'));
  });

}).call(this);
